# Generated by Django 5.1.1 on 2024-10-29 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_groups', '0003_alter_member_options_album_image_alter_album_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(null=True, upload_to='music_groups/albums', verbose_name='Обложка'),
        ),
        migrations.CreateModel(
            name='MemberImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='music_groups/members', verbose_name='Фотография')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music_groups.member', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Фотография участника',
                'verbose_name_plural': 'Фотографии участников',
            },
        ),
    ]
