# Generated by Django 5.1.1 on 2024-10-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_groups', '0004_alter_album_image_memberimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='music_groups/albums', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='memberimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='music_groups/members', verbose_name='Фотография'),
        ),
    ]
