# Generated by Django 5.1.1 on 2024-11-25 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_groups', '0007_album_user_genre_user_group_user_memberimage_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberimage',
            name='user',
        ),
    ]
